apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dask-scheduler
  name: dask-scheduler
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      app: dask-scheduler
    spec:
      containers:
      - args:
        - dask-scheduler
        image: quanted/daskdev-dask
        name: dask-scheduler
      hostname: dask-scheduler
      restartPolicy: Always