apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qed-nginx-deployment
  labels:
    app: qed-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qed-nginx
  template:
    metadata:
      labels:
        app: qed-nginx
    spec:
      containers:
      - name: qed-nginx
        image: qed_nginx_kube
      restartPolicy: Always