apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvolume-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: postgres-pv1
