apiVersion: v1
kind: PersistentVolume
metadata:
  name: qed-flask-pvolume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: flask-pv1
  hostPath:
    path: /Users/dsmith/Documents/git/qed_kube/data/pv-flask
