apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qed-django-deployment
  labels:
    app: qed-django-deployment
spec:
  replicas: 1
  template:
    metadata:
        labels:
            app: qed-django
    spec:
      containers:
        name: django
        image: quanted/qed_django:latest
        env:
        - name: REDIS_HOSTNAME
          value: redis
        - name: DOCKER_HOSTNAME
          value: $(HOSTNAME)           
        volumeMounts:
        - name: qed-templates
          mountPath: /src/templates_qed
        - name: qed-static
          mountPath: /src/static_qed
        - name: django-pVolume
          mountPath: /src/django_pVolume
      volumes:
      - hostPath:
          path: ./templates_qed
        name: qed-templates
      - hostPath:
          path: ./static_qed
        name: qed-static
      - name: django-pVolume
        persistentVolumeClaim:
          claimName: qed-django-pVolume-claim1