apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qed-celery-pVolume-claim1
spec:
  storageClassName: celery-pv1
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi