apiVersion: v1
kind: PersistentVolume
metadata:
  name: qed-celery-pVolume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: celery-pv1
  hostPath:
    path: ./data/pv-celery