apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qed-celery
  labels:
    app: qed-celery
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-celery
    spec:
      containers:
      - name: qed-celery
        image: quanted/flask_qed:dev
        imagePullPolicy: "Always"
        command:
        - celery
        - "worker"
        - "-A"
        - "celery_cgi"
        - "-Q"
        - "qed"
        - "--loglevel=INFO"
        - "-c"
        - "2"
        - "-n"
        - "qed_worker"
        env:
        - name: DOCKER_HOSTNAME
          value: QED-KUBERNETES
        - name: REDIS_HOSTNAME
          value: redis
        volumeMounts:
        - mountPath: /src/pram-flask/ubertool/ubertool/sam/bin/Preprocessed
          name: sam-preprocessed
        - mountPath: /src/pram-flask/ubertool/ubertool/sam/bin/Results
          name: sam-results
        - mountPath: /src/hms-flask/data/qed-basins
          name: qed-basins
        - mountPath: /src/pvolume
          name: celery-pvolume
      restartPolicy: Always
      volumes:
      - name: sam-preprocessed
        hostPath:
          path: /Users/dsmith/Documents/git/qed_kube/data/sam-preprocessed
          type: Directory
      - name: sam-results
        hostPath:
          path: /Users/dsmith/Documents/git/qed_kube/data/sam-results
          type: Directory
      - name: qed-basins
        hostPath:
          path: /Users/dsmith/Documents/git/qed_kube/data/qed-basins
          type: Directory
      - name: celery-pvolume
        persistentVolumeClaim:
          claimName: qed-celery-pvolume-claim1