apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qed-celery-pvolume-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: celery-pv1
