apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qed-flask
  labels:
    app: qed-flask
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-flask
    spec:
      containers:
      - name: qed-flask
        image: quanted/flask_qed:dev
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080
        env:
        - name: REDIS_HOSTNAME
          value: redis
        - name: DOCKER_HOSTNAME
          value: QED-KUBERNETES
        volumeMounts:
          - mountPath: /src/pram-flask/ubertool/ubertool/sam/bin/Preprocessed
            name: sam-preprocessed
          - mountPath: /src/pram-flask/ubertool/ubertool/sam/bin/Results
            name: sam-results
          - mountPath: /src/hms-flask/data/qed-basins
            name: qed-basins
          - mountPath: /src/pvolume
            name: flask-pvolume
      restartPolicy: Always
      volumes:
      - name: sam-preprocessed
        hostPath:
          path: /Users/dsmith/Documents/git/qed_kube/data/sam-preprocessed
          type: Directory
      - name: sam-results
        hostPath:
          path: /Users/dsmith/Documents/git/qed_kube/data/sam-results
          type: Directory
      - name: qed-basins
        hostPath:
          path: /Users/dsmith/Documents/git/qed_kube/data/qed-basins
          type: Directory
      - name: flask-pvolume
        persistentVolumeClaim:
          claimName: qed-flask-pvolume-claim1