apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pvolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: C:\git\qed_kube\data\tomcat-secrets\tomcat\chemaxon\licenses
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: redis-pv1
  volumeMode: Filesystem
