kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: qed-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443