apiVersion: v1
kind: Pod
metadata:
  name: qed-static
spec:
  containers:
    - name: static-volume
      image: busybox
      volumeMounts:
        - name: qed-static
          mountPath: /src/
        - name: qed-templates
          mountPath: /src/
  volumes:
    - name: qed-static
      hostPath:
        type: Directory
        path: static_qed
    - name: qed-templates
      hostPath:
        type: Directory
        path: templates_qed